name: test go action
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Teste
        uses: LeandroLS/test-go-action@main
      - name: Autocommit
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          commit_message: Update generated README
          branch: main
          commit_user_name: readme-scribe 🤖
          commit_user_email: actions@github.com
          commit_author: readme-scribe 🤖 <actions@github.com>
